version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-sgc
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: SGC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: